name: tenant-service

services:
  database:
    image: postgres:16
    container_name: tenant-service-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: test1234
      POSTGRES_DB: tenant-service-db
    ports:
      - "25432:5432"
    volumes:
      - ./docker/init-postgres/init-keycloak-db.sql:/docker-entrypoint-initdb.d/init-keycloak-db.sql
  kafka:
    image: apache/kafka:4.1.0
    container_name: tenant-service-kafka
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_LISTENERS: EXTERNAL://0.0.0.0:9092,CONTROLLER://0.0.0.0:9093
      KAFKA_ADVERTISED_LISTENERS: EXTERNAL://localhost:29092
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,EXTERNAL:PLAINTEXT
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@localhost:9093
      KAFKA_INTER_BROKER_LISTENER_NAME: EXTERNAL
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_NUM_PARTITIONS: 3
    ports:
      - "29092:9092"
  mailcatcher:
    restart: on-failure
    image: dockage/mailcatcher:0.9.0
    ports:
      - "1080:1080"
      - "1025:1025"
  keycloak:
    image: quay.io/keycloak/keycloak:26.7.3
    container_name: tenant-service-keycloak
    command: start-dev
    environment:
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://database:5432/keycloak-db
      KC_DB_USERNAME: postgres
      KC_DB_PASSWORD: test1234
      KC_BOOTSTRAP_ADMIN_USERNAME: admin
      KC_BOOTSTRAP_ADMIN_PASSWORD: admin
      KC_HOSTNAME: localhost
    ports:
      - "8080:8080"
    depends_on:
      - database