server.port=8180

spring.application.name=Tenant Service

spring.datasource.url=jdbc:postgresql://localhost:25432/tenant-service-db
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.username=postgres
spring.datasource.password=test1234

spring.jpa.hibernate.ddl-auto=none
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.liquibase.change-log=classpath:db/changelog/db.changelog-master.xml

spring.kafka.bootstrap-servers=localhost:29092
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.apache.kafka.common.serialization.ByteArraySerializer
spring.kafka.producer.properties.spring.json.add.type.headers=false

outbox.initial-delay=1s
outbox.fixed-delay=10s
outbox.max-attempts=5
outbox.message-lease=60s
outbox.message-poll-limit=200
outbox.renew-window=30s

logging.level.dev.shockman=TRACE
logging.level.org.hibernate=ERROR
logging.level.org.hibernate.SQL=OFF
logging.level.org.hibernate.orm.jdbc.bind=OFF
logging.level.org.hibernate.orm.jdbc.extract=OFF
logging.level.org.hibernate.stat=OFF

spring.mail.host=localhost
spring.mail.port=1025
spring.mail.username=your-email@gmail.com
spring.mail.password=your-app-password
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

tenant.identity.auth-url=http://localhost:8080/realms/test/protocol/openid-connect/auth
tenant.identity.issuer=http://localhost:8080/realms/test
tenant.identity.token-endpoint=http://localhost:8080/realms/test/protocol/openid-connect/token
tenant.identity.client-id=test
tenant.identity.client-secret=AcCU3VqR3VuFbc974Wb3xb1cmTWWWe9jelx5X9WbYQpFGNMaujdq66Cr77GLCqusFnE7rQGeRlgdVGvfmrGHOG
tenant.identity.jwks-url=http://localhost:8080/realms/test/protocol/openid-connect/certs
tenant.identity.scope=openid email

tenant.base-url=http://localhost:${server.port}