### Create a new realm
POST http://localhost:8180/api/v1/realms/create
Content-Type: application/json
Accept: application/json

{
  "name": "Test Realm4",
  "slug": "test-realm4"
}

> {%
    client.global.set("response", response)
 %}

### Get Existing Realm By Slug
GET http://localhost:8180/realms/test-realm
Accept: application/json

> {%
    client.global.set("id", response.body.id)

    client.test("Name and slug correct", function() {
        client.assert(response.body.name == "Test Realm")
        client.assert(response.body.slug == "test-realm")
    })
%}

### Deleting existing realm
DELETE http://localhost:8180/realms?id={{id}}