[versions]
spring-boot = "3.5.3"
kotlin = "2.2.0"
liquibase = "4.32.0"
postgres = "42.7.7"
junit-platform-launcher = "6.0.0-M1"
spring-dependency-management = "1.1.7"
jackson-kotlin = "2.19.1"
hypersistence-utils-hibernate-63 = "3.10.1"
authzed = "1.4.1"
grpc = "1.73.0"

[libraries]
spring-web = { module = "org.springframework.boot:spring-boot-starter-web", version.ref="spring-boot" }
spring-jpa = { module = "org.springframework.boot:spring-boot-starter-data-jpa", version.ref="spring-boot" }
spring-mail = { module = "org.springframework.boot:spring-boot-starter-mail", version.ref="spring-boot" }
spring-pulsar = { module = "org.springframework.boot:spring-boot-starter-pulsar", version.ref="spring-boot" }
spring-validation = { module = "org.springframework.boot:spring-boot-starter-validation", version.ref="spring-boot" }
spring-devtools = { module = "org.springframework.boot:spring-boot-devtools", version.ref="spring-boot" }
spring-test = { module = "org.springframework.boot:spring-boot-starter-test", version.ref="spring-boot" }

jackson-kotlin = { module = "com.fasterxml.jackson.module:jackson-module-kotlin", version.ref="jackson-kotlin" }
kotlin-reflect = { module = "org.jetbrains.kotlin:kotlin-reflect", version.ref="kotlin" }
liquibase = { module = "org.liquibase:liquibase-core", version.ref="liquibase" }
postgres = { module = "org.postgresql:postgresql", version.ref="postgres" }
kotlin-test = { module = "org.jetbrains.kotlin:kotlin-test-junit5", version.ref="kotlin" }
juint-platform-launcher = { module = "org.junit.platform:junit-platform-launcher", version.ref="junit-platform-launcher" }
hypersistence-utils-hibernate = { module = "io.hypersistence:hypersistence-utils-hibernate-63", version.ref = "hypersistence-utils-hibernate-63"}

authzed-api = { module = "com.authzed.api:authzed", version.ref = "authzed" }
grpc-api = { module = "io.grpc:grpc-api", version.ref = "grpc" }
grpc-stub = { module = "io.grpc:grpc-stub", version.ref = "grpc" }

[plugins]
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
kotlin-spring = { id = "org.jetbrains.kotlin.plugin.spring", version.ref = "kotlin" }
kotlin-jpa = { id = "org.jetbrains.kotlin.plugin.jpa", version.ref = "kotlin" }
spring-boot = { id = "org.springframework.boot", version.ref = "spring-boot" }
spring-management = { id = "io.spring.dependency-management", version.ref = "spring-dependency-management" }